"""
Data Source Resolver

Provides a single place to determine which raw dataset should
feed the feature engineering pipeline.

Supported sources
-----------------
batch
    Uses datasets generated by fetch_data_from_FEMAAPI.py

kafka
    Uses datasets generated by the Kafka streaming pipeline.
"""

from pathlib import Path

# Project root:
# direct_data_streaming/
_DS_ROOT = Path(__file__).resolve().parents[2]


def get_raw_directory(source: str = "batch") -> Path:
    """
    Return the raw data directory for the selected ingestion source.
    """

    source = source.lower()

    paths = {
        "batch": (
            _DS_ROOT
            / "src"
            / "ingestion"
            / "data"
            / "raw"
        ),

        "kafka": (
            _DS_ROOT
            / "data"
            / "raw"
        ),
    }

    if source not in paths:
        raise ValueError(
            f"Unknown source '{source}'. "
            f"Choose 'batch' or 'kafka'."
        )

    return paths[source]