"""
Canonical Raw Data Synchronization Utility

Synchronizes raw Parquet datasets generated by external ingestion
pipelines (e.g. Kafka streaming) into the canonical raw dataset
directory consumed by the feature engineering pipeline.

Author:
    Stephen O. Ogodo
"""

from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import Iterable


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger(__name__)


class RawDataSynchronizer:
    """
    Synchronize raw Parquet datasets into the project's canonical
    raw data directory.
    """

    DEFAULT_FILES = (
        "declarations.parquet",
        "disaster_summaries.parquet",
        "public_assistance.parquet",
    )

    def __init__(
        self,
        source_dir: Path,
        destination_dir: Path,
        files: Iterable[str] | None = None,
    ) -> None:

        self.source_dir = Path(source_dir)
        self.destination_dir = Path(destination_dir)
        self.files = tuple(files or self.DEFAULT_FILES)

    # -------------------------------------------------------------

    def validate(self) -> None:
        """Validate source directory and required files."""

        if not self.source_dir.exists():
            raise FileNotFoundError(
                f"Source directory not found:\n{self.source_dir}"
            )

        missing = [
            file
            for file in self.files
            if not (self.source_dir / file).exists()
        ]

        if missing:
            raise FileNotFoundError(
                "Missing required raw datasets:\n"
                + "\n".join(missing)
            )

    # -------------------------------------------------------------

    @staticmethod
    def _needs_copy(src: Path, dst: Path) -> bool:
        """
        Return True if destination doesn't exist or differs
        from source.
        """

        if not dst.exists():
            return True

        return (
            src.stat().st_size != dst.stat().st_size
            or int(src.stat().st_mtime) != int(dst.stat().st_mtime)
        )

    # -------------------------------------------------------------

    def synchronize(self) -> dict[str, int]:
        """
        Synchronize datasets.

        Returns
        -------
        dict
            Summary statistics.
        """

        self.validate()

        self.destination_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        copied = 0
        skipped = 0

        logger.info("=" * 70)
        logger.info("Canonical Raw Data Synchronization")
        logger.info("=" * 70)

        logger.info("Source      : %s", self.source_dir)
        logger.info("Destination : %s", self.destination_dir)
        logger.info("")

        for filename in self.files:

            src = self.source_dir / filename
            dst = self.destination_dir / filename

            if self._needs_copy(src, dst):

                shutil.copy2(src, dst)

                copied += 1

                logger.info("✓ Copied   %s", filename)

            else:

                skipped += 1

                logger.info("✓ Current  %s", filename)

        logger.info("")
        logger.info("-" * 70)
        logger.info("Copied  : %d", copied)
        logger.info("Current : %d", skipped)
        logger.info("Done.")

        return {
            "copied": copied,
            "current": skipped,
        }


# -------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------

if __name__ == "__main__":

    PROJECT_ROOT = Path(__file__).resolve().parents[3]

    SOURCE = PROJECT_ROOT / "data" / "raw"

    DESTINATION = (
        PROJECT_ROOT
        / "direct_data_streaming"
        / "src"
        / "ingestion"
        / "data"
        / "raw"
    )

    synchronizer = RawDataSynchronizer(
        source_dir=SOURCE,
        destination_dir=DESTINATION,
    )

    try:

        synchronizer.synchronize()

    except Exception as exc:

        logger.exception(exc)

        raise